# Generated by Django 4.2.8 on 2023-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gender_customuser_phone_number_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='detail',
        ),
        migrations.AddField(
            model_name='address',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Informasi tambahan, seperti patokan atau detail lainnya', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Jakarta', help_text='Kota/Kabupaten', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='Contoh Kecamatan', help_text='Kecamatan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='12345', help_text='Kode Pos', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='DKI Jakarta', help_text='Provinsi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='rt_rw',
            field=models.CharField(blank=True, help_text='RT/RW (opsional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='Jl. Contoh No. 123', help_text='Nama jalan dan nomor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='village',
            field=models.CharField(default='Contoh Kelurahan', help_text='Kelurahan/Desa', max_length=100),
            preserve_default=False,
        ),
    ] 