# Generated by Django 5.2 on 2025-04-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_restructure_address_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="image_url",
            new_name="profile_pic_url",
        ),
    ]
