# Generated by Django 5.2 on 2025-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View Transaction"),
                            ("status_change", "Status Change"),
                            ("cancel", "Cancel Transaction"),
                            ("unauthorized", "Unauthorized Access Attempt"),
                            ("suspicious", "Suspicious Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Pembayaran"),
                            ("paid", "Pembayaran Berhasil"),
                            ("processing", "Pesanan Diproses"),
                            ("failed", "Pembayaran Gagal"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "delivery_price",
                    models.DecimalField(decimal_places=2, default=25000, max_digits=10),
                ),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("processing", "Diproses"),
                            ("shipped", "Dikirim"),
                            ("delivered", "Diterima"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("shipping_address", models.TextField()),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_postal_code", models.CharField(max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("velocepay", "VelocePay")],
                        default="velocepay",
                        max_length=50,
                    ),
                ),
                (
                    "payment_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
