# Generated by Django 5.2 on 2025-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="delivery_price",
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("velocepay", "VelocePay")], default="velocepay", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="shipping_status",
            field=models.CharField(
                choices=[
                    ("processing", "Diproses"),
                    ("shipped", "Dikirim"),
                    ("delivered", "Diterima"),
                    ("cancelled", "Dibatalkan"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Menunggu Pembayaran"),
                    ("paid", "Pembayaran Berhasil"),
                    ("processing", "Pesanan Diproses"),
                    ("failed", "Pembayaran Gagal"),
                    ("cancelled", "Dibatalkan"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
