# Generated by Django 5.2 on 2025-04-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_transaction_payment_url_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Add column if not exists
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'transaction_transaction'
                    AND column_name = 'payment_url'
                ) THEN
                    ALTER TABLE transaction_transaction ADD COLUMN payment_url VARCHAR(255) NULL;
                END IF;
            END $$;
            """,
            # Reverse SQL - Do nothing since removing this column could cause data loss
            """
            -- No reverse migration
            """
        ),
    ]
