# Generated by Django 5.2 on 2025-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View Transaction"),
                    ("status_change", "Status Change"),
                    ("cancel", "Cancel Transaction"),
                    ("unauthorized", "Unauthorized Access Attempt"),
                    ("suspicious", "Suspicious Activity"),
                    ("add", "Add Product"),
                    ("edit", "Edit Product"),
                    ("delete", "Delete Product"),
                ],
                max_length=50,
            ),
        ),
    ]
