# Generated by Django 5.1.7 on 2025-03-24 17:43

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(
                max_length=255, unique=True, validators=[main.models.validate_email]
            ),
        ),
    ]
