# Generated by Django 5.2 on 2025-04-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("Nike", "Nike"), ("Adidas", "Adidas")], max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=50, unique=True)),
                ("price", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("men", "Men"),
                            ("women", "Women"),
                            ("unisex", "Unisex"),
                        ],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                ("image_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["brand", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField()),
                ("stock", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["size"],
                "unique_together": {("product", "size")},
            },
        ),
    ]
