# Generated by Django 5.2 on 2025-04-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("Nike", "Nike"), ("Adidas", "Adidas")], max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=50, unique=True)),
                ("price", models.IntegerField()),
                (
                    "size",
                    models.TextField(
                        help_text="Store sizes as JSON array, e.g. [36, 37, 38, 40, 42]"
                    ),
                ),
                ("image_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["brand", "name"],
            },
        ),
    ]
